### ISSUE TITLE
Loading spinner doesn't work in built version

### ISSUE THREAD

**Issue by Bettelstab** [nimiq/accounts#103]
Somehow the data url is different from the source.

**Comment by Bettelstab** [comment]
I remember investigating this before and it may be related to some bug in the interplay of vue-loader and postcss.

Temporarily resolved by https://github.com/nimiq/accounts/pull/104

**Comment by sisou** [comment]
Does #104 also resolve the issue in the Loader component? Or should we remove the CSS for the loading animation there and use the global definition of `loading.css`?

**Comment by sisou** [comment]
Fixed by #104 and new LoadingSpinner component in @nimiq/vue-components.
