### ISSUE TITLE
Integrate browser warnings

### ISSUE THREAD

**Issue by danimoh** [nimiq/accounts#105]
Integrate the browser warnings script we usually use to display warnings on outdated browsers, private tabs, etc..
Note that this should not be bundled into the main bundle to be able to run on old browsers that can not parse the main bundle due to syntax errors.

Maybe @Bettelstab could be interested in setting this up in webpack?

The newest revision of that script is in the getsome / onboarding app.
At this point we should probably also consider providing the browser-warnings via an own npm package.

**Comment by Bettelstab** [comment]
Solved by #231
