### ISSUE TITLE
Mobile onboarding

### ISSUE THREAD

**Issue by Bettelstab** [nimiq/accounts#113]
On mobile device, onboarding component is broader then the Screen.

**Comment by mariofriz** [comment]
Also saw that issue, I quickly threw something together, by stacking vertically

![image](https://user-images.githubusercontent.com/1634484/51307841-f8729a00-1a40-11e9-8a8e-d5ebe48dafbd.png)

Is this the desired behaviour ?
Also this component is in nimiq/vue-components, shouldn't it be in this repo ?

**Comment by danimoh** [comment]
Hello Mario.
Thank you.
The mobile design in general is still in the works, but yes the design our designer came up with is similar to your approach :)

I have the feeling too, that some elements should be moved around between `accounts`, `vue-components` and `safe`. We'll discuss it in the team at some point.

**Comment by sisou** [comment]
Fixed in https://github.com/nimiq/vue-components/commit/4868295ec2e366bdc7fe60580e7a3999c1b8257a
