### ISSUE TITLE
De-merge of soeren/merged

### ISSUE THREAD

**Issue by sisou** [nimiq/accounts#117]
- [x] c8fc3e76 - #104 
- [x] c9f145da - #104 
- [x] 5ab7309e - #106 
- [x] 47fd57f1 - #107 
- [x] d8581c50 - #135 
- [x] 7b5e1564 - $router.push => $rpc.routerPush (@sisou, include into #106 or #107, depending which gets merged first)
- [x] 4d03002b - Ignore shopLogoUrl (@sisou, re-check after Keyguard merge and new KeyguardClient build)
- [x] c6b1dc75 - #104 
- [x] 6ef8ded0 - #107 
- [x] 7b99a29d - merged `master`
- [x] db913123 - #107 
- [x] 85dcc851 - merged `master`
- [x] 47e26368 - #107 
- [x] 96393f9b - @Bettelstab new PR?
- [x] ee5a4a15 - #104 
- [x] 43953071 - #111 
- [x] e9d30118 - #132 
- [x] 5ca9112f - Revert 96393f9b
- [x] 14757d43 - #104 
- [x] 3bcface6 - new wording (@Bettelstab)
- [x] bd2bf8cd - new wording (@Bettelstab)
- [x] 12151c4d - Upgrade vue-components (@sisou)
- [x] 06d305f9 - wording (@Bettelstab)
- [x] 19af5b1b - Update vue-components with Daniel's style updates (@sisou)
- [x] 3bda3f8e - make linter happy (@Bettelstab)
- [x] 29b78de9 - loader for addAddress, height: 70.5rem for small-page (@nibhar)
- [x] 72e4fa898 - Transform LoginSuccess to pure Loader (@sisou)
- [x] 9ea093ac - Add success title slide-up to Loader (@sisou)
- [x] ec72230d - SimpleSuccess now uses Loader instead of Success (@nibhar)
- [x] a7ba871f - Fix endless-loop request for change-passphrase (@nibhar)
- [x] 277b2fc9 - Router mini-simplification, fix Login keyguard result type (@sisou)
- [x] 074126c3 - Use Loader in LogoutSuccess, fix Logout redirect loop (@sisou)
- [x] 70c2793d - Merge `max/choose-address` (@Bettelstab, new PR)
- [x] 586a7fc0 - Update vue-components for wording (@sisou)
- [x] cda7eb60 - After 'yarn' in Accounts, also execute yarn in Client (@nibhar, new PR)
- [x] ec8b2e5d - #104 
- [x] 2e55016d - Update @nimiq/keyguard-client, manage hasFile/hasWords flags for wallets (@sisou, new PR)
- [x] 7f2738c1 - Remove client yarn from Travis setup, as it's a postinstall hook now (@nibhar, include in postinstall PR)
- [x] a3095df8 - Use Muli on Demos page (@sisou, new PR)
- [x] a7f7a09e - Update @nimiq/style, /vue-components, /keyguard-client (@sisou, new PR after Keyguard merge done)
- [x] ca7a2745 - Handle hasFile/hasWords flags from export result (@sisou, include in hasFile/hasWords PR)
- [x] 2f396d63 - Fix request loop in Signup (@sisou, new PR)
- [x] 33139013 - Improve styling of ChooseAddress (@Bettelstab, include in choose-address PR)
- [x] aa545d45 - Client v0.1.0 (@sisou, new PR, release new AccountsClient)
- [x] 4acca39f - merge `master`
- [x] c2436fd7 - Add client README by copying root README during build, client v0.1.2 (@sisou, new PR)
- [x] b4ff8bbc - merge `master`
- [x] 72b0f5cc - Client v0.1.3
- [x] 4ec5e6d9 - use tld instead of full origin to determine default endpoint (@Bettelstab, new PR from `max/client-default-endpoint)
- [x] fdc0abfd - on testnet domain; accept all origins for now (should probably not be merged, @Bettelstab?)
- [x] 0d8a4e33 - Connect to correct Keyguard origin (@sisou, new PR)
- [x] b6556d17 - Fix linting error (@sisou)
- [x] 03b915b5 - Missed one Keyguard URL (@sisou, include in Keyguard origin PR)
- [x] 32edd5fe26a30036d86e247f2e94f42f59228fe2
- [x] 5f40bdafb03781eb74d0b7f1174a4a8e159189ef @Bettelstab Faucet PR
- [x] c9b4846ea04e64a93a06db29dd9791db2854acc7
- [x] 77f9948dcf6760998b3b1b9eccc75fb6d88d9636 @Bettelstab Faucet PR
- [x] d08bfa2dbb0a5c6ad951f9fe35556da1469fd98b
- [x] fed9c2ac2d10ae17ad1f22927e396903d3667d15
- [x] f81537a4b3e8fa83a85bdd4ff1bbaaa520602b1b @Bettelstab Faucet PR
- [x] 9852bc335f24510eb1de11d99faa8c460fc67fb6 https://github.com/nimiq/accounts/pull/164
- [x] 22791a491fa9b02f984767b97bcaba5e8e9fe2d1 https://github.com/nimiq/accounts/pull/164
- [x] 354952195fc94f77d8a669e5c0ffa601807d7843 https://github.com/nimiq/accounts/pull/125

**Comment by Bettelstab** [comment]
- Wording PR: Waiting for other PRs which change constants.ts
- fdc0abf should not be merged
- Todo: Choose address PR

**Comment by sisou** [comment]
All commits from `soeren/merged` are accounted for in `master` or in pending PRs.
