### ISSUE TITLE
Signup flow

### ISSUE THREAD

**Issue by Bettelstab** [nimiq/accounts#13]
- [x] selection: keyguard or ledger
- [x] call keyguard
- [x] receive answer from keyguard
- [x] choose label
- [x] success screen with info about what happened
- [ ] ledger wallets

**Comment by Bettelstab** [comment]
[ ] selection: keyguard or ledger
[ ] call keyguard
[ ] receive answer from keyguard
[ ] choose label
[ ] success screen with info about what happened

**Comment by sisou** [comment]
Label editing is covered in #20, Ledger wallets should also get their own issue.
