### ISSUE TITLE
Safari: Call migrate per Redirect

### ISSUE THREAD

**Issue by Bettelstab** [nimiq/accounts#137]
For migration to happen, we need to open Keyguard at toplevel. Pretending it already happened doesn't work well with autoincremented ids.

**Comment by sisou** [comment]
As I commented here, I think this is actually a non-issue and already happening:
https://github.com/nimiq/keyguard-next/pull/200#discussion_r257289192

Because a creation or import already opens the keyguard as top-level, thus running the migration directly, before storing a new key.

**Comment by sisou** [comment]
Additionally, the AM migrate call is already called as redirect anyway.
