### ISSUE TITLE
Testnet Safe attempts to onboard if the first account was made outside of the safe

### ISSUE THREAD

**Issue by MatthewDLudwig** [nimiq/accounts#203]
The Setup:
- Have no keyguard accounts logged in at https://safe.nimiq-testnet.com/
- Create an account on a site that isn't Nimiq Safe.  For example:
  - Go to https://old.drawpad.org/nimiq/testing/
  - Click on any of the buttons and when prompted to select an account you should see none.
  - Create a new account through the opened popup (referred to as `non-safe-account` when necessary).
    - You don't need to complete the action for the button and can close the popup.
    - Creating the account through a non Nimiq Safe site is all that's needed.

The Problem:  
- When you go to https://safe.nimiq-testnet.com/ you will be redirected to the onboarding process, even though you already have an account.
  - https://accounts.nimiq-testnet.com/onboard?id=358956472&returnURL=https%3A%2F%2Fsafe.nimiq-testnet.com%2F&command=onboard&args=%5B%7B"appName"%3A"Accounts"%7D%5D
- once you create the account on the safe it'll show you both accounts, so it's not like the first account gets lost / isn't seen by the safe.
  - It's just that the safe doesn't notice it at firsts, and forces you to create a new account.

Tested Scenarios:
- I've confirmed that this happens on both mobile devices and desktops.
- I've tested sending NIM to the `non-safe-account` and then visiting the Safe.
  - I was still prompted to onboard, but upon creating the second account I saw that the Safe was reporting "0 NIM" as the balance for the `non-safe-account`.
  - After a minute or two the safe caught up and the `non-safe-account` showed the correct balance.
  - So I couldn't prove whether or not the balance of the `non-safe-account` affects it as I don't know how ensure the Safe is synced up with consensus since I'm immediately redirected to onboarding.  I figure this kind of test is one only you guys can pull off by disabling the onboarding redirection, but I'll leave the rest to the pros!

**Comment by sisou** [comment]
I believe this is rather an issue in the Safe, where it is checking for accounts/wallets and redirecting before the iframe has a chance to load and fill the store. Safe is probably is not respecting the `hasAccounts` store property or the recent removal of the `keyguardReady` flag has something to do with it.

**Comment by Bettelstab** [comment]
Yes, Safe is not waiting for hasAccounts to become true.
