### ISSUE TITLE
Add extension protocols to allowed shopOrigins

### ISSUE THREAD

**Issue by MatthewDLudwig** [nimiq/accounts#223]
When using the Keyguard from a chrome extension, all functions work correctly except checkout which throws the following error: `InvalidRequest: shopOrigin protocol must be https: or http:`  This can be seen in my demo extension, which Soeren has a copy of and which has also been posted in the NimiqDevs telegram.

If it doesn't cause any security risks, I think it'd make sense to add the following to the list of acceptable protocols:

- "chrome-extension:" - Chrome + Brave + Opera + all other chromium based browers.
   - If Firefox has security risks, I'd be ok with only allowing chromium based extensions.  Many browser are moving this way including Microsoft Edge which is doing research into a chromium build.
- "moz-extension:" - Firefox

**Comment by MatthewDLudwig** [comment]
Dug up the exact error I'm getting:

```
InvalidRequest: shopOrigin protocol must be https: or http:
    at SignTransactionApi.parseShopOrigin (https://keyguard.nimiq-testnet.com/request/toplevel.1376dd71.js:763:23)
    at SignTransactionApi.parseRequest (https://keyguard.nimiq-testnet.com/request/sign-transaction/index.1376dd71.js:688:45)
    at async SignTransactionApi.request (https://keyguard.nimiq-testnet.com/request/toplevel.1376dd71.js:1138:31)
```

**Comment by sisou** [comment]
We decided to add `chrome-extension:` and `moz-extension:` to the whitelist. PR coming soon!
