### ISSUE TITLE
"Cancel" doesn't work in redirect case

### ISSUE THREAD

**Issue by Bettelstab** [nimiq/accounts#30]
E.g. "cancel payment" at the bottom. This is because currently it just calls window.close(), which is not allowed in redirect case. (Chrome 69)

**Comment by sisou** [comment]
Yes, you are right. Those need to be changed to reply an error, and in the keyguard to reply a specific error so that the accounts manager knows to forward it.

**Comment by sisou** [comment]
Fixed in nimiq/accounts with https://github.com/nimiq/accounts/commit/e6b3b95119928d00741afcf5e7e91746a1ae923b.
Fixed in nimiq/keyguard-next with https://github.com/nimiq/keyguard-next/pull/97.
