### ISSUE TITLE
[SUGGESTION] Use blockchain height from various APIs during checkout

### ISSUE THREAD

**Issue by sisou** [nimiq/accounts#38]
For the checkout flow, the AccountsManager receives only the most basic data about a transaction, such as recipient, amount, data. All other things, like the sender, fee and validityStartHeight needs to be added by the AccountsManager itself, before being able to sign it via the Keyguard.

Now, I don't want users to have to wait for consensus before signing the transaction (because they have to wait for it afterwards when relaying the transaction, too), so I suggest getting the current blockchain height from various independant APIs (nimiq.watch, nimiqx, nimiqo, mopsus come to mind initially) and comparing them. If they agree with each other within 1 or 2 blocks, then take the lower one. If they are further apart than a certain number of blocks, fall back to network.

This would be magnitutes of times faster than having to wait for consensus, which can 1. take a long time on spotty internet connection and 2. freeze the interface for a couple seconds.

What do think?

**Comment by Bettelstab** [comment]
Sounds reasonable to me.

Note: For popup case, it would still be possible to have consensus all the time in the accounts manager iframe.

Does the interface really freeze, despite running the network in an iframe? :(

**Comment by sisou** [comment]
Using test-api.nimiq.watch for now in the testnet, with a fallback to network consensus if the `fetch()` fails for any reason: https://github.com/nimiq/accounts/commit/c3ba427a9bdd3a532948618b1951e751867c880b.

**Comment by sisou** [comment]
Fixed by 'pico' consensus.
