### ISSUE TITLE
Integrate Nimiq Network

### ISSUE THREAD

**Issue by paberr** [nimiq/accounts#7]
- [x] Checking existing repos and how to do it best.

Resulting tasks:
- [x] Adapting Boruca Messaging Lib to new @nimiq/rpc library.
- [x] Checking @nimiq/network API.
- [x] Integrating @nimiq/network into @nimiq/accounts.

**Comment by Bettelstab** [comment]
Aren't we done with that?

**Comment by sisou** [comment]
We have the `Network` component now providing the `NanoNetworkApi`, yes.
