### ISSUE TITLE
Detect active accounts by transaction history (and balance)

### ISSUE THREAD

**Issue by sisou** [nimiq/accounts#94]
Instead of just by balance.

**Comment by danimoh** [comment]
Copying my reply from PR#91 (for reference):

The nano-api currently supports a method `requestTransactionHistory`, ideally we'd however only ask for transaction receipts, which is much cheaper to calculate.
On the other hand of course one doesn't import accounts that often... So for now requestTransactionHistory could be ok.
Implementing `requestTransactionReceipts` however will be useful at some point, as it will also be required by the cashlink lib.

No, I'd say accounts that have transactions OR a balance. An account that has a balance without (incoming) transactions is a rare corner case though. It would be either a genesis account (these are all legacy wallets though for which we don't have to run the account finding anyways) or accounts that mined a block. So we could also drop the "OR a balance" part to make the call cheaper.

**Comment by sisou** [comment]
I think miner accounts should be found too, good point. So I'd say transaction receipts first and for all other accounts in that GAP also check the balance.
